# Name of workflow
name: gendiff CI

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  build:
    # The type of machine to run the job on
    runs-on: ubuntu-latest
    strategy:
      # Python versions list
      matrix:
        python-version: [3.10]
    steps:
        # Check-out repository under GitHub workspace
        # https://github.com/actions/checkout
      - uses: actions/checkout@v4
        # Step's name
      - name: Set up Python ${{ matrix.python-version }}
        # Configures the Python version used on GitHub-hosted runners
        # https://github.com/actions/setup-python
        uses: actions/setup-python@v5
        with:
          # The Python version to configure
          python-version: ${{ matrix.python-version }}
        # make depends on poetry
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      
      - name: Run check
        run: make check

      - name: Run linter
        run: make lint
      
      - name: Run test
        run: make test

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-cov
          debug: true